site_name: alembic_utils_extended
site_description: Autogenerate Support for PostgreSQL Functions and (soon) Views

theme:
    name: 'readthedocs'

extra_css:
    - css/custom.css

repo_name: candidhealth/alembic-utils-extended
repo_url: https://github.com/candidhealth/alembic-utils-extended
site_url: https://candidhealth.github.io/alembic-utils-extended

nav:
    - Introduction: 'index.md'
    - Quickstart: 'quickstart.md'
    - API Reference: 'api.md'
    - Configuration: 'config.md'
    - Examples: 'examples.md'

markdown_extensions:
  - codehilite
  - admonition
  - mkautodoc
