"""Keep autogenerated ops in dependency order across fork-managed objects and
stock table changes.

Background
----------
On Alembic >= 1.18 the schema-level comparators run through a
``PriorityDispatcher``. ``AutogenContext`` branches the *global* comparator
registry — where this library installs its ``@comparators.dispatch_for("schema")``
functions (``compare_registered_entities``, ``compare_indexes``,
``compare_check_constraints``) — *before* Alembic merges in its built-in table
comparator. All of them register at the default ``MEDIUM`` priority, and within a
priority the dispatch order is insertion order, so the fork's comparators end up
running *before* the built-in table diff. Every comparator does
``upgrade_ops.ops.append(...)``, so the fork's create ops land in
``upgrade_ops.ops`` ahead of ``CreateTableOp`` and the generated migration tries
to create a trigger / function / index before the table it depends on.

(Before Alembic 1.18 the built-in comparators registered onto the shared
dispatcher first, so creates were already ordered correctly — the bug is specific
to the priority dispatcher, hence the version guard below.)

Fix
---
Register a ``LAST``-priority ``"schema"`` comparator. It runs after every
``MEDIUM`` comparator (the built-in table diff included) and rewrites
``upgrade_ops.ops`` as ``[library drops, stock ops, library creates]``:

* library **creates** move after all stock ops → tables/columns exist before the
  entities/indexes/constraints that depend on them (upgrade correctness);
* library **drops** move before all stock ops → dependents are dropped before the
  tables they hang off of.

Downgrade is produced by ``upgrade_ops.reverse_into(downgrade_ops)`` *after* this
comparator runs, so reordering the upgrade list makes both directions correct.
The relative order within each group is preserved (entities keep the order
``solve_resolution_order`` chose; stock keeps Alembic's FK-aware order).
"""
from __future__ import annotations

from alembic.autogenerate import comparators
from alembic.autogenerate.api import AutogenContext
from alembic.operations import MigrateOperation, ops

from alembic_utils_extended.reversible_op import CreateOp, DropOp, ReplaceOp

try:
    # ``DispatchPriority`` / the priority dispatcher are new in Alembic 1.18.
    from alembic.util.langhelpers import DispatchPriority
except ImportError:  # pragma: no cover - Alembic < 1.18 orders creates correctly already
    DispatchPriority = None

# Top-level ops emitted by this library's comparators. They depend on the tables
# and columns managed by stock Alembic, so on upgrade they must come after stock
# ops and on downgrade before them. Stock Alembic nests its own index/constraint
# ops inside ``ModifyTableOps``; only the fork appends these at the top level.
_LIBRARY_CREATE_OPS = (CreateOp, ReplaceOp, ops.CreateIndexOp, ops.CreateCheckConstraintOp)
_LIBRARY_DROP_OPS = (DropOp, ops.DropIndexOp, ops.DropConstraintOp)


def reorder_upgrade_ops(upgrade_ops: ops.UpgradeOps) -> None:
    """Rewrite ``upgrade_ops.ops`` to ``[library drops, stock ops, library creates]``."""
    drops: list[MigrateOperation] = []
    stock: list[MigrateOperation] = []
    creates: list[MigrateOperation] = []
    for op in upgrade_ops.ops:
        if isinstance(op, _LIBRARY_DROP_OPS):
            drops.append(op)
        elif isinstance(op, _LIBRARY_CREATE_OPS):
            creates.append(op)
        else:
            stock.append(op)
    upgrade_ops.ops[:] = drops + stock + creates


if DispatchPriority is not None:

    @comparators.dispatch_for("schema", priority=DispatchPriority.LAST)
    def reorder_library_ops(
        autogen_context: AutogenContext,
        upgrade_ops: ops.UpgradeOps,
        schemas: list[str | None],
    ) -> None:
        """Runs after all MEDIUM comparators; see the module docstring."""
        reorder_upgrade_ops(upgrade_ops)
